name = "mandelbrot-f"
version = "0.1.0"
license = "license"
author = "Jesper Olsen"
maintainer = "43079279+jesper-olsen@users.noreply.github.com"
copyright = "Copyright 2024, Jesper Olsen"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
